### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by sjtuztq** [dparrini/python-comtrade#12]
rec.load(fileCFG,fileDAT)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 0: ordinal not in range(128)

**Comment by dparrini** [comment]
Hi @sjtuztq , I pushed a commit addressing this issue.

a1026ad06e96eae0eb84814128fe03f5c5e93c75

Let me know if it worked for you. In case it don't fix the issue, please provide an anonymized version of the `fileCFG` file, keeping any special character there. Thanks

**Comment by LFBJC** [comment]
@dparrini I have a similar issue, when using the version 0.0.4 it raises a "**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 7: invalid continuation byte**", so I had to downgrade to version 0.0.3 in order to read some of the oscillographies, but the version 0.0.3 doesn't read all oscillographies because of some issues with this version

**Comment by dparrini** [comment]
Hi @LFBJC I'll take a look into this, thanks for bringing this up. I'm updating the code to handle issue #18  and hope I can fix this one as well.

**Comment by dparrini** [comment]
@LFBJC I disabled utf-8 decoding in the most recent commit to fix #18 issue. Let me know if this works for you.

**Comment by LFBJC** [comment]
I think something that may help is that in my case I could read these oscillographies on version 0.0.3, I think it's because of [this commit](https://github.com/dparrini/python-comtrade/commit/a1026ad06e96eae0eb84814128fe03f5c5e93c75) what issue where you trying to address when you did this?

**Comment by LFBJC** [comment]
@dparrini still the same problem
![image](https://user-images.githubusercontent.com/29292837/129865152-52f12be3-e333-4dba-9526-7c464bba38ce.png)

**Comment by LFBJC** [comment]
@dparrini I just noted that the version I installed from pip (0.0.4) doesn't have the most recent commits, but that's the last version on pip, how should I install it?

**Comment by dparrini** [comment]
Hi @LFBJC , I pushed a new commit fb09c66012fe36c03c88cc2e7fbe797e48ad8a0a with what I think is a fix to the problem you're having. I didn't release a version in pip with this new commit yet but will if it solves your issue.
You can repeat the test you did by downloading the most recent comtrade.py file.

Let me know if it works. Thanks for your patience.
/David

**Comment by LFBJC** [comment]
Hi @dparrini I tried again, it raised another exception, but I think you're getting there.
![image](https://user-images.githubusercontent.com/29292837/130073368-8abb4fab-68ec-49ac-b26a-0e8f6b56ca43.png)

**Comment by LFBJC** [comment]
I did a pull request

**Comment by dparrini** [comment]
Great @LFBJC , thank you for your support on this!

**Comment by LFBJC** [comment]
@dparrini no worries! tell me when you release a version in pip

**Comment by dparrini** [comment]
@LFBJC just published it.
