### ISSUE TITLE
cannot pack non-iterable NoneType object

### ISSUE THREAD

**Issue by nolanbell** [dparrini/python-comtrade#15]
It doesn't like this time: 1:56:36.201868 (one digit in front).

This cfg file is from SEL 751A.

**Comment by engineerjoe440** [comment]
Hi @nolanbell ! Is this related to #16 ? It looks like the issues might be related, but it would be helpful to confirm. If that's the case, I might be able to offer a little assistance. Can't guarantee anything, but I'd be more than happy to take a look!

**Comment by engineerjoe440** [comment]
@dparrini: this issue can be closed.
