### ISSUE TITLE
reading COMTRADE files and getting a convert string to float error

### ISSUE THREAD

**Issue by spark706** [dparrini/python-comtrade#31]
I have files from new SEL-735 PQ meters that when downloaded from the relay itself as a COMTRADE file, will cause a string to float conversion error. 

> C:/Users/spark/Desktop/Comtrade Files/New folder/ZIGZAG_735 - ER 10015 15_57_54_736.cfg
> Traceback (most recent call last):
>   File "c:\Users\nv7\Dropbox\files\PyCharm\COMTRADE-Reader\735plot.py", line 34, in <module>
>     rec.load(sel_file + '.cfg', sel_file + '.dat')
>   File "c:\Users\nv7\Dropbox\files\PyCharm\COMTRADE-Reader\comtrade.py", line 754, in load
>     self._load_cfg_dat(cfg_file, dat_file)
>   File "c:\Users\nv7\Dropbox\files\PyCharm\COMTRADE-Reader\comtrade.py", line 767, in _load_cfg_dat
>     self._cfg.load(cfg_filepath)
>   File "c:\Users\nv7\Dropbox\files\PyCharm\COMTRADE-Reader\comtrade.py", line 324, in load
>     self._read_io(cfg)
>   File "c:\Users\nv7\Dropbox\files\PyCharm\COMTRADE-Reader\comtrade.py", line 454, in _read_io
>     self._time_multiplier = float(line)
> ValueError: could not convert string to float: '1 \x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a'

I looked into the cfg file and noticed a additional space for null data

> 1,IA,A, ,A,   0.06466082,0,0,-32768,32767,   80.0000,1,P
> 2,IB,B, ,A,   0.06466082,0,0,-32768,32767,   80.0000,1,P
> 3,IC,C, ,A,   0.06466082,0,0,-32768,32767,   80.0000,1,P
> 4,IN,N, ,A,   0.06466082,0,0,-32768,32767,   80.0000,1,P
> 5,VA,A, ,V,   0.03667481,0,0,-32768,32767,    1.0000,1,P
> 6,VB,B, ,V,   0.03667481,0,0,-32768,32767,    1.0000,1,P
> 7,VC,C, ,V,   0.03667481,0,0,-32768,32767,    1.0000,1,P

which I removed but then I get a further errors of a similar type. The script I am using has been functional in the past when I have received an SEL event report file with a cev format and then converted it with SEL SynchroWAVE but this is the first time dealing directly with the relay COMTRADE file itself.  I tested to see if a file converted from SEL's SynchroWAVE software, which can convert to 1999 and 2013 formats, caused any issues as both binary and ascii formats but they all worked.

Attached is one COMTRADE file that is not sensitive in nature and is causing the error.
[files.zip](https://github.com/dparrini/python-comtrade/files/8006757/files.zip)

**Comment by dparrini** [comment]
Hi @spark706 , thanks for reaching out and attaching a sample. The text files (both .cfg and .hdr) doesn't end on EOF, but on a sequence of 0x1A ([substitute character](https://en.wikipedia.org/wiki/Substitute_character)), which are not handled by python's method such as `strip()`.

![image](https://github.com/dparrini/python-comtrade/assets/6284749/48f9a341-c450-4144-8e8b-ccb2f1a7c6c1)

I updated the module so it will remove these characters of last lines of cfg files and both hdr/inf files. This solves the issue for the attached sample.
