### ISSUE TITLE
Test UTF-8 fail

### ISSUE THREAD

**Issue by vicnet** [dparrini/python-comtrade#32]
On linux, Centos 7 with python 3, I have a fail assertion:
> FAIL: test_utf8_check (tests.tests.TestEncodingHandling)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>  File "/data/vincent/sources/projects/rte/rspace/dev/python-comtrade/tests/tests.py", line 417, in test_utf8_check
>    self.assertTrue(comtrade._file_is_utf8("tests/sample_files/sample_ascii_utf-8.cfg"))
> AssertionError: False is not true

The test use `_file_is_utf8` that use itself `_stream_is_utf8` that try to open and read the file without locale.
python3 is now natively in utf-8 so the read could not send any exception...
Perhaps this consideration is no more useful...

**Comment by dparrini** [comment]
Thanks, you're absolutely right. I think at the time it was intended for backward compatibility with Python 2.7 but I've never added it anyway.
