### ISSUE TITLE
re.time match nonetype error

### ISSUE THREAD

**Issue by R-Ormrod** [dparrini/python-comtrade#34]
line 65 of contrade.py causes an error on some comtrade files as it expects only 2 numbers after the second ':'

this line should read
re_time = re.compile(r"([0-9]{1,2}):([0-9]{2}):([0-9]{1,2})(\.([0-9]{1,12}))?")

allowing 1, or 2 values in that position.

**Comment by dparrini** [comment]
Hi, @R-Ormrod , thanks for the solution! It's now integrated.
