### ISSUE TITLE
Wrong timestamps in sample_files/

### ISSUE THREAD

**Issue by tieugene** [dparrini/python-comtrade#38]
According to 2013:
- CFG: Data/time stamps must have "ss.ssssss: ...minimum length = 9 characters (microseconds), maximum length =
12 characters (nanoseconds)".
- DAT: "timestamp: ...Base unit of time is microseconds or nanoseconds depending on the
definition of the date/time stamp in the CFG file"

`sample_ascii.cfg` and others:
```
12/01/2011,05:55:30.75011
12/01/2011,05:55:30.78261
```

**Comment by dparrini** [comment]
Hi, thanks for pointing this out. The module always padded values with length lower than 6, so it is not a bug per se, but an invalid value indeed.
