### ISSUE TITLE
TypeError for a specific type of DR file

### ISSUE THREAD

**Issue by SidhartheneeNayak** [dparrini/python-comtrade#46]
I had used the Python comtrade to read and extract a DR file into Python but it is giving a type error. I have attached the screenshot of the DR file when opened in wavewin and the error screenshot.

Steps to reproduce:
`rec = Comtrade()
rec.load(r"path\1e4c815f-275d-49ca-a7cf-1f75a728037b.cfg",
         R"path\1e4c815f-275d-49ca-a7cf-1f75a728037b.dat")
print("Trigger time = {}s".format(rec.trigger_time))`

<img width="406" alt="ss2" src="https://github.com/dparrini/python-comtrade/assets/57494002/52ae9fbf-f0a9-4f64-8983-f4e61fcc37a7">
<img width="960" alt="ss1" src="https://github.com/dparrini/python-comtrade/assets/57494002/198f1c90-69d3-4f52-a922-5e022591d40a">

Due to privacy issue, I cannot share the .dat and .cfg files of the DR so I attached the screenshots of the error and the code to reproduce it.

**Comment by U-RxI** [comment]
Hi @SidhartheneeNayak,
The error may relate to the format of the two timestamps in the .cfg file.
Please, check that they are formatted in accordance with the comtrade standard.
"dd/mm/yyyy,hh:mm:ss.ssssss" for revisions >1991.
The number of decimals after the dot relates to the resolution "ssssss" -> microseconds and "sssssssss" -> nanoseconds. 
You can find them in them around the bottom of the .cfg file. 
Based on the snip from Wavewin, it could indicate that the dot is missing ("11:28:18581309.000").

![image](https://github.com/dparrini/python-comtrade/assets/22933539/c332db7b-f62b-4712-adbf-b5a19e033ae0)

**Comment by SidhartheneeNayak** [comment]
@U-RxI thanks for pointing this out :)
